# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf00b0f5076ebe65d240de4dd941f242e33ba61a398b00cc867878e4daa48cca7d2f4e0b6360708a3e1e8bb3c974409225868bf21c208713f1c427e2a754a5b4

test:
  secret_key_base: d977171c4a2c8bebd293bedc982f474d73416e4ccca43118006093fb70051e256b02f6a30cf015a6afb9ae7c7cc8ddd799cf327d1679c5926ee027e2d8a5f32b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
